### ISSUE TITLE
Форма тренажера

### ISSUE THREAD

**Issue by RomanDMWB** [KoJlJlaPs/LanguagePractick-#6]
Кароче нужно создать макет такой чтобы можно было использовать и на мобилках типа маленький, в форме должно быть:
Текст задания типа там переведите на англ или на русский(как пример)
Потом поле помнишь в билетах ГИБДД там были формы где задания без фото, типа не во всех тренажерках будут фото
Затем input для ввода ответа
Ну и кнопка для отправки
Еще есть вариант типа добавить внизу полосу состояния типа сколько вопросов осталось
Ну это типа пока то что я дцмаю можно добавить в форму

**Comment by KoJlJlaPs** [comment]
Бля чекни пока что, ветка dev сделал парашу какую-то.
Если честно нахуя радио баттоны ?
Функция же на проверку значения, можно просто с обычной кнопки значение брать? не? 
Отпишись потом, что и как надо  еще раз, можно скринами

**Comment by KoJlJlaPs** [comment]
На счет фоток:
Так если фотки нет-поставим фотку что фотки нет))) Вот и все

**Comment by KoJlJlaPs** [comment]
![image](https://user-images.githubusercontent.com/87981197/211898496-5b429a24-e174-4896-846b-039c44161e58.png)

**Comment by KoJlJlaPs** [comment]
Пока что так

**Comment by RomanDMWB** [comment]
Молодец соси конец

**Comment by RomanDMWB** [comment]
Скоро сделаю добавлю апи

**Comment by RomanDMWB** [comment]
Отлично сделано
![image](https://user-images.githubusercontent.com/109600484/218282435-368a350b-43ab-4d35-849d-64314152331c.png)
ваще супер, можешь отдыхать под пивко
