### ISSUE TITLE
#dev:Вход и регистрация

### ISSUE THREAD

**Issue by KoJlJlaPs** [KoJlJlaPs/LanguagePractick-#8]

**Comment by KoJlJlaPs** [comment]
Нужно сделать окно входа и регистрации на главной странице

**Comment by RomanDMWB** [comment]
Типа модалки хочешь сделать?

**Comment by KoJlJlaPs** [comment]
Ну тип такого
чекай

**Comment by KoJlJlaPs** [comment]
![image](https://user-images.githubusercontent.com/87981197/203149035-cdd2042c-6634-4d18-b43d-786bb0856ec9.png)

**Comment by KoJlJlaPs** [comment]
при нажатии должна такая фигня вылезти

**Comment by KoJlJlaPs** [comment]
![image](https://user-images.githubusercontent.com/87981197/204157181-3ef0aad0-8247-4629-a845-7c0c2c29f031.png)

**Comment by KoJlJlaPs** [comment]
Я думаю так сойдет пока что
